repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.3  
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0  
    hooks:
      - id: mypy